#############################################################################
# Makefile for building: output/debug/ddesigner
# Generated by qmake (2.01a) (Qt 4.8.4) on: Thu May 16 22:40:27 2013
# Project:  ddesigner.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile ddesigner.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DDEBUG -DQT_SVG_LIB -DQT_XMLPATTERNS_LIB -DQT_XML_LIB -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -std=c++0x -g -Wall -Wno-parentheses -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtXml -I/usr/include/qt4/QtXmlPatterns -I/usr/include/qt4/QtSvg -I/usr/include/qt4 -I. -I.. -I/usr/X11R6/include -I.tmp/debug -I.tmp/debug
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -L/usr/X11R6/lib -lqjson -lQtSvg -lQtXmlPatterns -lQtXml -lQtOpenGL -lQtGui -lQtCore -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = .tmp/debug/

####### Files

SOURCES       = mainwindow.cpp \
		main.cpp \
		nodetype/nodetypecategoryitem.cpp \
		nodetype/nodetypecategoryitemconnector.cpp \
		nodetype/nodetypelistwidget.cpp \
		nodetype/nodetypeitem.cpp \
		nodetype/optionsstackedwidget.cpp \
		diagram/diagramscene.cpp \
		diagram/diagramview.cpp \
		diagram/items/nodelabelitem.cpp \
		diagram/items/linkitem.cpp \
		diagram/items/nodesvgitem.cpp \
		diagram/modes/noactionmode.cpp \
		diagram/modes/diagrammode.cpp \
		diagram/modes/moveitemmode.cpp \
		diagram/modes/linkmode.cpp \
		diagram/modes/addnodesvgitemmode.cpp \
		diagram/items/nodeitem.cpp \
		diagram/items/linkanchor.cpp \
		diagram/diagramcontroller.cpp \
		diagram/items/linkpathitem.cpp .tmp/debug/moc_mainwindow.cpp \
		.tmp/debug/moc_nodetypecategoryitemconnector.cpp \
		.tmp/debug/moc_nodetypelistwidget.cpp \
		.tmp/debug/moc_optionsstackedwidget.cpp \
		.tmp/debug/moc_diagramview.cpp \
		.tmp/debug/qrc_icons.cpp
OBJECTS       = .tmp/debug/mainwindow.o \
		.tmp/debug/main.o \
		.tmp/debug/nodetypecategoryitem.o \
		.tmp/debug/nodetypecategoryitemconnector.o \
		.tmp/debug/nodetypelistwidget.o \
		.tmp/debug/nodetypeitem.o \
		.tmp/debug/optionsstackedwidget.o \
		.tmp/debug/diagramscene.o \
		.tmp/debug/diagramview.o \
		.tmp/debug/nodelabelitem.o \
		.tmp/debug/linkitem.o \
		.tmp/debug/nodesvgitem.o \
		.tmp/debug/noactionmode.o \
		.tmp/debug/diagrammode.o \
		.tmp/debug/moveitemmode.o \
		.tmp/debug/linkmode.o \
		.tmp/debug/addnodesvgitemmode.o \
		.tmp/debug/nodeitem.o \
		.tmp/debug/linkanchor.o \
		.tmp/debug/diagramcontroller.o \
		.tmp/debug/linkpathitem.o \
		.tmp/debug/moc_mainwindow.o \
		.tmp/debug/moc_nodetypecategoryitemconnector.o \
		.tmp/debug/moc_nodetypelistwidget.o \
		.tmp/debug/moc_optionsstackedwidget.o \
		.tmp/debug/moc_diagramview.o \
		.tmp/debug/qrc_icons.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		ddesigner.pri \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/declarative_debug.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		ddesigner.pro
QMAKE_TARGET  = ddesigner
DESTDIR       = output/debug/
TARGET        = output/debug/ddesigner

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): .tmp/debug/ui_mainwindow.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) output/debug/ || $(MKDIR) output/debug/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9]\+\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: ddesigner.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		ddesigner.pri \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/declarative_debug.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib/x86_64-linux-gnu/libQtSvg.prl \
		/usr/lib/x86_64-linux-gnu/libQtXmlPatterns.prl \
		/usr/lib/x86_64-linux-gnu/libQtXml.prl \
		/usr/lib/x86_64-linux-gnu/libQtOpenGL.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile ddesigner.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
ddesigner.pri:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/declarative_debug.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/opengl.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib/x86_64-linux-gnu/libQtSvg.prl:
/usr/lib/x86_64-linux-gnu/libQtXmlPatterns.prl:
/usr/lib/x86_64-linux-gnu/libQtXml.prl:
/usr/lib/x86_64-linux-gnu/libQtOpenGL.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile ddesigner.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/debug/ddesigner1.0.0 || $(MKDIR) .tmp/debug/ddesigner1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/debug/ddesigner1.0.0/ && $(COPY_FILE) --parents mainwindow.h nodetype/nodetypecategoryitem.h nodetype/nodetypecategoryitemconnector.h nodetype/nodetypelistwidget.h nodetype/nodetypeitem.h nodetype/optionsstackedwidget.h diagram/diagramscene.h diagram/diagramview.h diagram/fourdirection.h diagram/diagramcontroller.h diagram/items/nodelabelitem.h diagram/items/linkitem.h diagram/items/nodesvgitem.h diagram/items/nodeitem.h diagram/items/linkanchor.h diagram/items/linkpathitem.h diagram/modes/noactionmode.h diagram/modes/diagrammode.h diagram/modes/moveitemmode.h diagram/modes/linkmode.h diagram/modes/addnodesvgitemmode.h diagram/itemdata.h .tmp/debug/ddesigner1.0.0/ && $(COPY_FILE) --parents icons.qrc .tmp/debug/ddesigner1.0.0/ && $(COPY_FILE) --parents mainwindow.cpp main.cpp nodetype/nodetypecategoryitem.cpp nodetype/nodetypecategoryitemconnector.cpp nodetype/nodetypelistwidget.cpp nodetype/nodetypeitem.cpp nodetype/optionsstackedwidget.cpp diagram/diagramscene.cpp diagram/diagramview.cpp diagram/items/nodelabelitem.cpp diagram/items/linkitem.cpp diagram/items/nodesvgitem.cpp diagram/modes/noactionmode.cpp diagram/modes/diagrammode.cpp diagram/modes/moveitemmode.cpp diagram/modes/linkmode.cpp diagram/modes/addnodesvgitemmode.cpp diagram/items/nodeitem.cpp diagram/items/linkanchor.cpp diagram/diagramcontroller.cpp diagram/items/linkpathitem.cpp .tmp/debug/ddesigner1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/debug/ddesigner1.0.0/ && (cd `dirname .tmp/debug/ddesigner1.0.0` && $(TAR) ddesigner1.0.0.tar ddesigner1.0.0 && $(COMPRESS) ddesigner1.0.0.tar) && $(MOVE) `dirname .tmp/debug/ddesigner1.0.0`/ddesigner1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/debug/ddesigner1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: .tmp/debug/moc_mainwindow.cpp .tmp/debug/moc_nodetypecategoryitemconnector.cpp .tmp/debug/moc_nodetypelistwidget.cpp .tmp/debug/moc_optionsstackedwidget.cpp .tmp/debug/moc_diagramview.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) .tmp/debug/moc_mainwindow.cpp .tmp/debug/moc_nodetypecategoryitemconnector.cpp .tmp/debug/moc_nodetypelistwidget.cpp .tmp/debug/moc_optionsstackedwidget.cpp .tmp/debug/moc_diagramview.cpp
.tmp/debug/moc_mainwindow.cpp: diagram/items/nodelabelitem.h \
		diagram/fourdirection.h \
		mainwindow.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o .tmp/debug/moc_mainwindow.cpp

.tmp/debug/moc_nodetypecategoryitemconnector.cpp: nodetype/nodetypecategoryitem.h \
		nodetype/nodetypeitem.h \
		nodetype/nodetypecategoryitemconnector.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) nodetype/nodetypecategoryitemconnector.h -o .tmp/debug/moc_nodetypecategoryitemconnector.cpp

.tmp/debug/moc_nodetypelistwidget.cpp: nodetype/nodetypecategoryitem.h \
		nodetype/nodetypeitem.h \
		nodetype/nodetypelistwidget.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) nodetype/nodetypelistwidget.h -o .tmp/debug/moc_nodetypelistwidget.cpp

.tmp/debug/moc_optionsstackedwidget.cpp: nodetype/optionsstackedwidget.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) nodetype/optionsstackedwidget.h -o .tmp/debug/moc_optionsstackedwidget.cpp

.tmp/debug/moc_diagramview.cpp: diagram/diagramscene.h \
		diagram/items/nodeitem.h \
		diagram/fourdirection.h \
		diagram/items/nodelabelitem.h \
		diagram/items/linkanchor.h \
		diagram/itemdata.h \
		diagram/items/linkitem.h \
		diagram/modes/diagrammode.h \
		diagram/diagramview.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) diagram/diagramview.h -o .tmp/debug/moc_diagramview.cpp

compiler_rcc_make_all: .tmp/debug/qrc_icons.cpp
compiler_rcc_clean:
	-$(DEL_FILE) .tmp/debug/qrc_icons.cpp
.tmp/debug/qrc_icons.cpp: icons.qrc \
		resources/style/ddesigner.css \
		resources/icons/maintoolbar/grid.png \
		resources/icons/maintoolbar/edit.png \
		resources/icons/maintoolbar/file.png \
		resources/icons/tools/move.png \
		resources/icons/tools/node.png \
		resources/icons/tools/search-grey.png \
		resources/icons/tools/search.png \
		resources/icons/tools/arrow-3-left.png \
		resources/icons/tools/link.png \
		resources/icons/tools/arrow-3-up.png \
		resources/icons/tools/arrow-3-down.png \
		resources/icons/tools/arrow-3-right.png
	/usr/lib/x86_64-linux-gnu/qt4/bin/rcc -name icons icons.qrc -o .tmp/debug/qrc_icons.cpp

compiler_image_collection_make_all: .tmp/debug/qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) .tmp/debug/qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: .tmp/debug/ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) .tmp/debug/ui_mainwindow.h
.tmp/debug/ui_mainwindow.h: mainwindow.ui \
		diagram/diagramview.h \
		nodetype/nodetypelistwidget.h \
		nodetype/optionsstackedwidget.h \
		diagram/diagramscene.h \
		diagram/items/nodeitem.h \
		diagram/fourdirection.h \
		diagram/items/nodelabelitem.h \
		diagram/items/linkanchor.h \
		diagram/itemdata.h \
		diagram/items/linkitem.h \
		diagram/modes/diagrammode.h \
		nodetype/nodetypecategoryitem.h \
		nodetype/nodetypeitem.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic mainwindow.ui -o .tmp/debug/ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

.tmp/debug/mainwindow.o: mainwindow.cpp mainwindow.h \
		diagram/items/nodelabelitem.h \
		diagram/fourdirection.h \
		.tmp/debug/ui_mainwindow.h \
		diagram/diagramview.h \
		diagram/diagramscene.h \
		diagram/items/nodeitem.h \
		diagram/items/linkanchor.h \
		diagram/itemdata.h \
		diagram/items/linkitem.h \
		diagram/modes/diagrammode.h \
		nodetype/nodetypelistwidget.h \
		nodetype/nodetypecategoryitem.h \
		nodetype/nodetypeitem.h \
		nodetype/optionsstackedwidget.h \
		noshiftproxystyle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp/debug/mainwindow.o mainwindow.cpp

.tmp/debug/main.o: main.cpp mainwindow.h \
		diagram/items/nodelabelitem.h \
		diagram/fourdirection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp/debug/main.o main.cpp

.tmp/debug/nodetypecategoryitem.o: nodetype/nodetypecategoryitem.cpp nodetype/nodetypecategoryitem.h \
		nodetype/nodetypeitem.h \
		nodetype/nodetypecategoryitemconnector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp/debug/nodetypecategoryitem.o nodetype/nodetypecategoryitem.cpp

.tmp/debug/nodetypecategoryitemconnector.o: nodetype/nodetypecategoryitemconnector.cpp nodetype/nodetypecategoryitemconnector.h \
		nodetype/nodetypecategoryitem.h \
		nodetype/nodetypeitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp/debug/nodetypecategoryitemconnector.o nodetype/nodetypecategoryitemconnector.cpp

.tmp/debug/nodetypelistwidget.o: nodetype/nodetypelistwidget.cpp nodetype/nodetypelistwidget.h \
		nodetype/nodetypecategoryitem.h \
		nodetype/nodetypeitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp/debug/nodetypelistwidget.o nodetype/nodetypelistwidget.cpp

.tmp/debug/nodetypeitem.o: nodetype/nodetypeitem.cpp nodetype/nodetypeitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp/debug/nodetypeitem.o nodetype/nodetypeitem.cpp

.tmp/debug/optionsstackedwidget.o: nodetype/optionsstackedwidget.cpp nodetype/optionsstackedwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp/debug/optionsstackedwidget.o nodetype/optionsstackedwidget.cpp

.tmp/debug/diagramscene.o: diagram/diagramscene.cpp diagram/diagramscene.h \
		diagram/items/nodeitem.h \
		diagram/fourdirection.h \
		diagram/items/nodelabelitem.h \
		diagram/items/linkanchor.h \
		diagram/itemdata.h \
		diagram/items/linkitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp/debug/diagramscene.o diagram/diagramscene.cpp

.tmp/debug/diagramview.o: diagram/diagramview.cpp diagram/diagramview.h \
		diagram/diagramscene.h \
		diagram/items/nodeitem.h \
		diagram/fourdirection.h \
		diagram/items/nodelabelitem.h \
		diagram/items/linkanchor.h \
		diagram/itemdata.h \
		diagram/items/linkitem.h \
		diagram/modes/diagrammode.h \
		diagram/modes/noactionmode.h \
		diagram/modes/moveitemmode.h \
		diagram/diagramcontroller.h \
		diagram/modes/addnodesvgitemmode.h \
		diagram/items/nodesvgitem.h \
		diagram/modes/linkmode.h \
		diagram/items/linkpathitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp/debug/diagramview.o diagram/diagramview.cpp

.tmp/debug/nodelabelitem.o: diagram/items/nodelabelitem.cpp diagram/items/nodelabelitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp/debug/nodelabelitem.o diagram/items/nodelabelitem.cpp

.tmp/debug/linkitem.o: diagram/items/linkitem.cpp diagram/items/linkitem.h \
		diagram/items/linkanchor.h \
		diagram/itemdata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp/debug/linkitem.o diagram/items/linkitem.cpp

.tmp/debug/nodesvgitem.o: diagram/items/nodesvgitem.cpp diagram/items/nodesvgitem.h \
		diagram/fourdirection.h \
		diagram/items/nodeitem.h \
		diagram/items/nodelabelitem.h \
		diagram/items/linkanchor.h \
		diagram/itemdata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp/debug/nodesvgitem.o diagram/items/nodesvgitem.cpp

.tmp/debug/noactionmode.o: diagram/modes/noactionmode.cpp diagram/modes/noactionmode.h \
		diagram/modes/diagrammode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp/debug/noactionmode.o diagram/modes/noactionmode.cpp

.tmp/debug/diagrammode.o: diagram/modes/diagrammode.cpp diagram/modes/diagrammode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp/debug/diagrammode.o diagram/modes/diagrammode.cpp

.tmp/debug/moveitemmode.o: diagram/modes/moveitemmode.cpp diagram/modes/moveitemmode.h \
		diagram/modes/diagrammode.h \
		diagram/diagramview.h \
		diagram/diagramscene.h \
		diagram/items/nodeitem.h \
		diagram/fourdirection.h \
		diagram/items/nodelabelitem.h \
		diagram/items/linkanchor.h \
		diagram/itemdata.h \
		diagram/items/linkitem.h \
		diagram/diagramcontroller.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp/debug/moveitemmode.o diagram/modes/moveitemmode.cpp

.tmp/debug/linkmode.o: diagram/modes/linkmode.cpp diagram/modes/linkmode.h \
		diagram/diagramview.h \
		diagram/diagramscene.h \
		diagram/items/nodeitem.h \
		diagram/fourdirection.h \
		diagram/items/nodelabelitem.h \
		diagram/items/linkanchor.h \
		diagram/itemdata.h \
		diagram/items/linkitem.h \
		diagram/modes/diagrammode.h \
		diagram/diagramcontroller.h \
		diagram/items/linkpathitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp/debug/linkmode.o diagram/modes/linkmode.cpp

.tmp/debug/addnodesvgitemmode.o: diagram/modes/addnodesvgitemmode.cpp diagram/modes/addnodesvgitemmode.h \
		diagram/modes/diagrammode.h \
		diagram/diagramview.h \
		diagram/diagramscene.h \
		diagram/items/nodeitem.h \
		diagram/fourdirection.h \
		diagram/items/nodelabelitem.h \
		diagram/items/linkanchor.h \
		diagram/itemdata.h \
		diagram/items/linkitem.h \
		diagram/diagramcontroller.h \
		diagram/items/nodesvgitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp/debug/addnodesvgitemmode.o diagram/modes/addnodesvgitemmode.cpp

.tmp/debug/nodeitem.o: diagram/items/nodeitem.cpp diagram/items/nodeitem.h \
		diagram/fourdirection.h \
		diagram/items/nodelabelitem.h \
		diagram/items/linkanchor.h \
		diagram/itemdata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp/debug/nodeitem.o diagram/items/nodeitem.cpp

.tmp/debug/linkanchor.o: diagram/items/linkanchor.cpp diagram/items/linkanchor.h \
		diagram/itemdata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp/debug/linkanchor.o diagram/items/linkanchor.cpp

.tmp/debug/diagramcontroller.o: diagram/diagramcontroller.cpp diagram/diagramcontroller.h \
		diagram/diagramview.h \
		diagram/diagramscene.h \
		diagram/items/nodeitem.h \
		diagram/fourdirection.h \
		diagram/items/nodelabelitem.h \
		diagram/items/linkanchor.h \
		diagram/itemdata.h \
		diagram/items/linkitem.h \
		diagram/modes/diagrammode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp/debug/diagramcontroller.o diagram/diagramcontroller.cpp

.tmp/debug/linkpathitem.o: diagram/items/linkpathitem.cpp diagram/items/linkpathitem.h \
		diagram/items/linkanchor.h \
		diagram/itemdata.h \
		diagram/items/linkitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp/debug/linkpathitem.o diagram/items/linkpathitem.cpp

.tmp/debug/moc_mainwindow.o: .tmp/debug/moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp/debug/moc_mainwindow.o .tmp/debug/moc_mainwindow.cpp

.tmp/debug/moc_nodetypecategoryitemconnector.o: .tmp/debug/moc_nodetypecategoryitemconnector.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp/debug/moc_nodetypecategoryitemconnector.o .tmp/debug/moc_nodetypecategoryitemconnector.cpp

.tmp/debug/moc_nodetypelistwidget.o: .tmp/debug/moc_nodetypelistwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp/debug/moc_nodetypelistwidget.o .tmp/debug/moc_nodetypelistwidget.cpp

.tmp/debug/moc_optionsstackedwidget.o: .tmp/debug/moc_optionsstackedwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp/debug/moc_optionsstackedwidget.o .tmp/debug/moc_optionsstackedwidget.cpp

.tmp/debug/moc_diagramview.o: .tmp/debug/moc_diagramview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp/debug/moc_diagramview.o .tmp/debug/moc_diagramview.cpp

.tmp/debug/qrc_icons.o: .tmp/debug/qrc_icons.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .tmp/debug/qrc_icons.o .tmp/debug/qrc_icons.cpp

####### Install

install_resources: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/home/hmartinet/QtProjects/ddesigner/output/debug/ || $(MKDIR) $(INSTALL_ROOT)/home/hmartinet/QtProjects/ddesigner/output/debug/ 
	-$(INSTALL_FILE) /home/hmartinet/QtProjects/ddesigner/resources/ddesigner.svg $(INSTALL_ROOT)/home/hmartinet/QtProjects/ddesigner/output/debug/
	-$(INSTALL_DIR) /home/hmartinet/QtProjects/ddesigner/resources/icons $(INSTALL_ROOT)/home/hmartinet/QtProjects/ddesigner/output/debug/
	-$(INSTALL_DIR) /home/hmartinet/QtProjects/ddesigner/resources/library $(INSTALL_ROOT)/home/hmartinet/QtProjects/ddesigner/output/debug/
	-$(INSTALL_DIR) /home/hmartinet/QtProjects/ddesigner/resources/style $(INSTALL_ROOT)/home/hmartinet/QtProjects/ddesigner/output/debug/


uninstall_resources:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/hmartinet/QtProjects/ddesigner/output/debug/ddesigner.svg 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/hmartinet/QtProjects/ddesigner/output/debug/icons 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/hmartinet/QtProjects/ddesigner/output/debug/library 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/hmartinet/QtProjects/ddesigner/output/debug/style
	-$(DEL_DIR) $(INSTALL_ROOT)/home/hmartinet/QtProjects/ddesigner/output/debug/ 


install:  install_resources  FORCE

uninstall: uninstall_resources   FORCE

FORCE:

